export const CONTENTFUL_CACHE_ENABLED_ENV = "CONTENTFUL_CACHE_ENABLED";
export const CONTENTFUL_REVALIDATE_SECONDS_ENV = "CONTENTFUL_REVALIDATE_SECONDS";
export const CONTENTFUL_CACHE_ENABLED_VALUE = "true";
export const DEFAULT_CONTENTFUL_REVALIDATE_SECONDS = 60;
export const CACHE_CONTROL_HEADER = "Cache-Control";
export const NO_STORE_CACHE_CONTROL = "no-store";
export const STALE_WHILE_REVALIDATE_MULTIPLIER = 5;
export const CONTENTFUL_PRODUCTS_CACHE_TAG = "contentful-products";
