export const PRODUCT_CARD_CLASS_NAMES = {
    article: "vitan-product-card flex h-full min-w-0 cursor-pointer flex-col overflow-hidden rounded-[var(--radius-lg)] bg-[rgba(var(--card-shade),var(--card-shade),var(--card-shade),0.5)] backdrop-blur-[var(--card-blur)] backdrop-saturate-[190%] backdrop-brightness-[1.1] transition-transform duration-200 active:scale-[0.99]",
    imageWrapper: "relative pt-1 px-1 pb-3",
    imageScroller: "flex w-full snap-x overflow-x-auto rounded-[var(--radius-md)] shadow-[inset_0_0_0_1px_rgba(255,255,255,0.3),0_2px_8px_rgba(0,0,0,0.06)] [-ms-overflow-style:none] [scrollbar-width:none] [&::-webkit-scrollbar]:hidden",
    imageButton: "group relative block aspect-square w-full flex-none cursor-zoom-in snap-start overflow-hidden rounded-[var(--radius-md)] focus-visible:outline-2 focus-visible:outline-offset-[-2px] focus-visible:outline-[var(--accent)] md:aspect-auto md:h-[247px] xl:h-[266px]",
    imagePlaceholder: "flex aspect-square w-full items-center justify-center rounded-[var(--radius-md)] bg-[rgba(255,255,255,0.15)] text-[var(--text-tertiary)] shadow-[inset_0_0_0_1px_rgba(255,255,255,0.3),0_2px_8px_rgba(0,0,0,0.06)] md:aspect-auto md:h-[247px] xl:h-[266px]",
    image: "h-full w-full object-cover transition-transform duration-300 group-hover:scale-[1.02]",
    imageDots: "absolute bottom-4 left-0 right-0 z-10 flex items-center justify-center gap-1.5",
    imageDot: "h-1.5 w-1.5 rounded-full bg-white/70 shadow-[0_0_2px_rgba(0,0,0,0.5)] transition-all duration-300 ease-out",
    activeImageDot: "h-1.5 w-4 rounded-full bg-white shadow-[0_0_3px_rgba(0,0,0,0.5)] transition-all duration-300 ease-out",
    favoriteOverlay: "absolute bottom-5 right-3 z-10 inline-flex h-11 w-11 items-center justify-center rounded-[var(--radius-md)] bg-black/25 shadow-[0_1px_3px_rgba(0,0,0,0.15)] backdrop-blur-md text-white transition-all duration-200 active:scale-[0.85]",
    favoriteOverlayActive: "absolute bottom-5 right-3 z-10 inline-flex h-11 w-11 items-center justify-center rounded-[var(--radius-md)] bg-black/25 shadow-[0_1px_3px_rgba(0,0,0,0.15)] backdrop-blur-md text-white transition-all duration-200 active:scale-[0.85]",
    content: "flex flex-1 gap-1 flex-col pt-1 p-3",
    contentInfo: "flex flex-1 flex-col gap-2",
    title: "line-clamp-2 min-w-0 break-words text-[17px] font-semibold leading-[22px] tracking-[-0.3px] text-[var(--text-primary)]",
    categoryRow: "flex flex-wrap gap-1.5",
    category: "w-fit rounded-full bg-black/8 px-2.5 py-1 text-[12px] font-semibold leading-4 text-[var(--text-secondary)]",
    descriptionWrapper: "flex flex-col gap-0.5",
    description: "line-clamp-1 text-[14px] leading-5 text-[var(--text-secondary)]",
    descriptionExpanded: "text-[14px] leading-5 text-[var(--text-secondary)]",
    descriptionToggle: "self-start text-[13px] font-semibold leading-4 text-[var(--text-primary)]",
    footer:"flex flex-col gap-1 mt-[2px]",
    priceUsd: "text-[15px] font-bold leading-5 tracking-[-0.2px] text-[var(--text-primary)] md:text-[18px] md:leading-6",
    priceUah: "text-[13px] font-medium leading-[18px] text-[var(--text-secondary)]",
};
