export const WISHLIST_CLASS_NAMES = {
    page: "min-h-screen px-4 py-5 pb-36 text-[#17150c] min-[744px]:px-8 min-[1024px]:pb-8",
    header: "mx-auto flex max-w-5xl items-center justify-between gap-4",
    title: "text-2xl font-black uppercase tracking-[0.16em] min-[744px]:text-3xl",
    backLink: "liquid-button-soft rounded-full px-4 py-2 text-sm font-semibold text-[#5f554d] transition-transform hover:scale-[1.03]",
    content: "mx-auto grid max-w-5xl gap-4 pt-5",
    emptyState: "liquid-surface rounded-3xl p-6 text-sm text-[#6b615b]",
    list: "grid gap-3",
    item: "liquid-surface grid gap-3 rounded-3xl p-3 min-[744px]:grid-cols-[120px_1fr_auto] min-[744px]:items-center",
    image: "aspect-[16/10] w-full rounded-2xl object-cover min-[744px]:aspect-square",
    itemInfo: "grid gap-1",
    category: "text-xs uppercase tracking-wide text-[#98887e]",
    name: "text-base font-semibold",
    price: "text-sm font-semibold text-[#336651]",
    controls: "flex flex-wrap items-center justify-between gap-2 min-[744px]:justify-end",
    cartButton: "liquid-button rounded-full px-4 py-2 text-sm font-semibold text-white transition-transform hover:scale-[1.03]",
    activeCartButton: "liquid-button-success rounded-full px-4 py-2 text-sm font-semibold text-white transition-transform hover:scale-[1.03]",
    removeButton: "liquid-button-danger rounded-full px-4 py-2 text-sm font-semibold text-[#8c2d1d] transition-transform hover:scale-[1.03]",
    summary: "liquid-button rounded-3xl p-5 text-white",
    summaryRow: "flex items-center justify-between gap-4 text-sm font-semibold",
    summaryTotal: "mt-2 flex items-center justify-between gap-4 text-lg font-bold",
};
